# Generated by Django 6.0.4 on 2026-04-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_alter_tweet_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='tweet_media/'),
        ),
    ]
