# Generated by Django 6.0.4 on 2026-04-21 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_alter_like_created_at_alter_retweet_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='parent_tweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tweets.tweet'),
        ),
    ]
