# Generated by Django 6.0.4 on 2026-04-27 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_alter_tweet_parent_tweet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['user', 'created_at'], name='idx_tweet_user_created'),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['parent_tweet', 'created_at'], name='idx_tweet_parent_created'),
        ),
        migrations.AlterModelTable(
            name='tweet',
            table='tweets_tweet',
        ),
    ]
